spring.application.name=spring-ecommerce-order

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

security.jwt.token.secret-key=${TOKEN_SECRET_KEY}
security.jwt.token.expire-length-ms=${TOKEN_EXPIRE_LENGTH}

spring.sql.init.mode=always
spring.config.import=optional:file:.env[.properties]

# from JPA
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.url=${SPRING_DATASOURCE_URL}

spring.jpa.open-in-view=false

## Stripe
stripe.secret-key=${STRIPE_SECRET_KEY}
